services:
  event-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-api
    user: "1000:1000"
    environment:
      - DATABASE_URL=file:./prisma/dev.db
    expose:
      - 3000
    volumes:
      - ./prisma:/app/prisma
    command: sh -c "pnpm prisma migrate deploy && node dist/src/index.js"
    networks:
      - integrate

networks:
  integrate:
    external: true
